ansible_host: "{{ inventory_hosts.pi_03 }}"
dhcp_mac: "e4:5f:01:56:f1:71"

display:
  type: ssd1306
  i2c_bus: 1
  i2c_address: "0x3C"

restic_node_name: pi-03
restic_postgres_dumps: []

compose_projects:
  - name: kavita
    dir: /opt/kavita
  - name: uptime-kuma
    dir: /opt/uptime-kuma
  - name: homepage
    dir: /opt/homepage
