all:
  children:
    fw:
      hosts:
        pi-fw:
    switch:
      hosts:
        mikrotik-sw:
    pi_nodes:
      children:
        comms:
          hosts:
            pi-01:
        data:
          hosts:
            pi-02:
        nas:
          hosts:
            pi-nas:
        utility:
          hosts:
            pi-03:
        control:
          hosts:
            pi-04:
        pi4_nodes:
          hosts: {}  # not yet deployed
