colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[profileMode]
  enabled = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  sharingLinks = []

[list]
  showBreadcrumbs = false
  showTableOfContents = false
  showSummary = true
  groupByYear = true

[sitemap]
  excludedKinds = []
